# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Rogelio Olvera
title: MBA Marketing & Data Analyst
email: rogelioolveram@gmail.com
website: https://rogerolvera.github.io/

# Dark Mode (true/false/never)
darkmode: never

# Social links
# twitter_username: facespics
github_username:  RogerOlvera
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: rogelioolveram
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
#- title: itsgoingto.be
  # icon: fas fa-globe
  # url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: Acerca de m칤
about_subtitle: Analista de datos con MBA en Negocios de Mercadotecnia
about_profile_image: https://drive.google.com/file/d/1zum0IX-3HEclzMakthTvTKBE1KPBKXVt/view?usp=drive_link
about_content: | # this will include new lines to allow paragraphs 

   游녿  Profesional con m치s de 15 a침os de experiencia en gesti칩n comercial basada en el an치lisis de datos y respaldado por un MBA en Negocios de Mercadotecnia. 


  游눹游댠 Recientemente conclu칤 un bootcamp de tecnolog칤a para profundizar mis conocimientos como Analista de datos, Python, SQL y an치lisis estad칤stico de negocios. 


  游댍   Proporciono experiencia en el an치lisis de oportunidades de negocio para la mejora continua de los procesos y maximizar el retorno de inversi칩n.


  游늶游늵 Mi experiencia incluye: 
 
  <mark>An치lisis de mercado basado en datos</mark> 
  <mark>Definici칩n de estrategias comerciales con inteligencia de negocio</mark>
  <mark>Tests A / B</mark>
  <mark>Segmentaci칩n de mercado (Clusters)</mark>
  <mark>Programas de lealtad basado en an치lisis de datos</mark>
  <mark>B2B & B2C</mark>
  <mark>ROI basado en datos</mark>
  <mark>Administraci칩n de presupuestos, estimaciones y aplicaciones</mark>
  <mark>Transformaci칩n digital</mark>
  <mark>Omnicanalidad</mark>
  <mark>Automatizaci칩n de trade marketing</mark> 
  <mark>Desarrollo de dashboards</mark>
  <mark>Visualizaci칩n de datos</mark>
  <mark>Desarrollo de modelos predictivos</mark>
  <mark>Desarrollo de modelos de Machine Learning</mark>

content:
  - title: Proyectos # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Retenci칩n de clientes en gimnasio
        link: https://github.com/RogerOlvera/Proyecto_13_pronostico_retencion_gimnasio
        # link_text: Project Website
        additional_links:
          - title:  Repositorio en Github
            icon: fab fa-github
            url: https://github.com/RogerOlvera/Proyecto_13_pronostico_retencion_gimnasio
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Muchos clientes van y vienen, pero 쯖칩mo podemos predecir qui칠nes se quedar치n y qui칠nes se ir치n?
        description: | # this will include new lines to allow paragraphs
          En este proyecto utiliz칩 t칠cnicas de an치lisis de datos para pronosticar la retenci칩n de clientes en un gimnasio, as칤 como su perfil de cliente. Utilizando un conjunto de datos de clientes de gimnasio, se desarroll칩 un modelo predictivo que permite identificar a los clientes con mayor probabilidad de abandonar el gimnasio y tomar medidas para retenerlos.

  - title: Experiencia # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: AB Inbev Grupo Modelo
        link: https://www.grupomodelo.com/
        # link_text: boringcompany.com
        sub_title: Gerente nacional de canal tradicional
        caption: Agosto 2006 - Abril 2022
        quote: >
          Transformando los procesos comerciales a trav칠s de la automatizaci칩n y el an치lisis de datos. 
        description: | # this will include new lines to allow paragraphs
          Durante mi tiempo en Grupo Modelo, lider칠 la transformaci칩n digital de los procesos comerciales del canal tradicional, implementando estrategias de automatizaci칩n y an치lisis de datos para mejorar la eficiencia y efectividad de las operaciones y ventas del canal. He trabajado en estrecha colaboraci칩n con equipos multifuncionales para desarrollar e implementar estrategias comerciales basadas en datos que impulsaron el crecimiento y la rentabilidad.

  - title: Educaci칩n # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Tripleten
        caption: Sep 2024 - Sep 2025
        sub_title: Bootcamp de Data Analyst
        quote: >
          Las habilidades que he adquirido en este bootcamp me han permitido profundizar en el an치lisis de datos, Python, SQL y an치lisis estad칤stico de negocios.
        description: | # this will include new lines to allow paragraphs
          En este bootcamp, he aprendido a utilizar herramientas y t칠cnicas avanzadas de an치lisis de datos para extraer informaci칩n valiosa de grandes conjuntos de datos. He adquirido habilidades en Python, SQL y an치lisis estad칤stico de negocios, lo que me ha permitido desarrollar modelos predictivos y realizar an치lisis complejos para tomar decisiones informadas.
      - layout: left
        title: Universidad Tec Milenio
        caption: Oct 2009 - Ago 2011
        sub_title: MBA en Negocios de Mercadotecnia
        quote: >
          Mi MBA en Negocios de Mercadotecnia me ha proporcionado una s칩lida base en estrategias comerciales y an치lisis de mercado.
        description: | # this will include new lines to allow paragraphs
          Durante mi MBA, he adquirido conocimientos en estrategias comerciales, an치lisis de mercado y gesti칩n de proyectos. He aprendido a desarrollar e implementar estrategias comerciales efectivas basadas en datos y a utilizar herramientas de an치lisis para tomar decisiones informadas. Mi formaci칩n me ha permitido comprender las din치micas del mercado y c칩mo aprovecharlas para impulsar el crecimiento y la rentabilidad de las empresas.

  - title: Un poco m치s sobre m칤
    layout: text
    content: | # this will include new lines to allow paragraphs
      Adicional a mi experiencia profesional, tengo una amplia gama de intereses y pasatiempos que me apasionan. Me encanta aprender cosas nuevas y siempre estoy buscando formas de mejorar mis habilidades y conocimientos. Algunos de mis pasatiempos incluyen:
      
      - Gaming, sobre todo juegos de peleas
      - Conciertos y festivales de m칰sica
      - Viajar y explorar nuevos lugares
      - Caminatas junto a mi cachorro
      

    # Look at this cool image  
    # ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
